/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practicamb_1;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.solr.client.solrj.SolrClient;
import org.apache.solr.client.solrj.SolrQuery;
import org.apache.solr.client.solrj.SolrServerException;
import org.apache.solr.client.solrj.impl.HttpSolrClient;
import org.apache.solr.client.solrj.request.CoreAdminRequest;
import org.apache.solr.client.solrj.response.CoreAdminResponse;
import org.apache.solr.client.solrj.response.QueryResponse;
import org.apache.solr.common.SolrDocumentList;
import org.apache.solr.common.SolrInputDocument;
import org.apache.solr.common.params.CoreAdminParams;

/**
 *
 * @author jhony
 */
public class Menu extends javax.swing.JFrame {

    SolrDocumentList docs = new SolrDocumentList(), trecDoc = new SolrDocumentList();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indexaBtn = new javax.swing.JButton();
        consultaBtn = new javax.swing.JButton();
        trecBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        indexaBtn.setText("Indexar Documento");
        indexaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexaBtnActionPerformed(evt);
            }
        });

        consultaBtn.setText("Consulta");
        consultaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBtnActionPerformed(evt);
            }
        });

        trecBtn.setText("Trec Eva");
        trecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trecBtnActionPerformed(evt);
            }
        });

        textInfo.setEditable(false);
        textInfo.setColumns(20);
        textInfo.setRows(5);
        jScrollPane1.setViewportView(textInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(indexaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trecBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(358, 358, 358))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(indexaBtn)
                .addGap(18, 18, 18)
                .addComponent(consultaBtn)
                .addGap(30, 30, 30)
                .addComponent(trecBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indexaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexaBtnActionPerformed
        // TODO add your handling code here:
        try {
            Scanner sc = null;
            String state = "b", index = null, title = null, author = null, text = null,
                    line, parts[];
            String url = "http://localhost:8983/solr";
            if (hasCollection(url)) {
                int opc = JOptionPane.showConfirmDialog(null, "Solr has documents, do you want to reset?");
                if (opc == 0) {
                    // Reset Colecciones
                    DeletingAllDocuments();
                }
            }
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter("All Files", "*.*"));
            int result = fileChooser.showOpenDialog(null);
            File file = null;
            if (result == JFileChooser.APPROVE_OPTION) {
                file = fileChooser.getSelectedFile();
            }

            sc = new Scanner(file);
            //  leemos
            while (sc.hasNextLine()) {
                state = "p";
                line = sc.nextLine();
                //System.out.println(line);
                //  indice
                if (line.startsWith(".I", 0)) {
                    indexaDocumento(index, title, author, text);
                    parts = line.split(" ");
                    index = parts[1];
                    //  System.out.println(index);
                }
                if (line.startsWith(".T", 0)) {
                    title = sc.nextLine();
                }
                if (line.startsWith(".A", 0)) {
                    author = sc.nextLine();
                }
                if (line.startsWith(".W", 0) || "READING".equals(state)) {  //texto 
                    text = sc.nextLine();
                    state = "READING";
                }
                if ("READING".equals(state)) {  //texto del documento 
                    String part = sc.nextLine();
                    if (part.startsWith(".X", 0)) {
                        state = "IGNORING";
                    } else {
                        text = text + part;
                    }
                    if ((line.startsWith(".X", 0)) || "IGNORING".equals(state)) {  //referencias cruzadas del documento     
                        //no hago nada
                    } else {
                        //aquí tampoco
                    }
                }
            }
            indexaDocumento(index, title, author, text);
            JOptionPane.showMessageDialog(null, "Document Indexed");
        } catch (SolrServerException | IOException | NullPointerException ex) {

            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }


    }//GEN-LAST:event_indexaBtnActionPerformed

    private void consultaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBtnActionPerformed
        // TODO add your handling code here:
        try {
            Scanner sc = null;
            String text = null, line;
            JFileChooser fileChooser = new JFileChooser();
            //fileChooser.setFileFilter(new FileNameExtensionFilter("All Files", "*.*"));
            int result = fileChooser.showOpenDialog(null);
            File file = null;
            if (result == JFileChooser.APPROVE_OPTION) {
                file = fileChooser.getSelectedFile();
            }

            sc = new Scanner(file);
            while (sc.hasNextLine()) {
                line = sc.nextLine();
                //System.out.println(line);
                //  indice
                if (line.startsWith(".W", 0)) {
                    //desc.add(line);
                    text = sc.next() + " ";
                    for (int i = 0; i < 4; i++) {
                        text = text + sc.next() + " ";
                    }
                    text = text.replaceAll("[\\[\\](){}]", "");
                    searchDocuments(text);
                }
                text = "";

            }

        } catch (HeadlessException | IOException | SolrServerException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Error al realizar consulta.");
        }
    }//GEN-LAST:event_consultaBtnActionPerformed

    private void trecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trecBtnActionPerformed
        // TODO add your handling code here:
        try {
            if (trecDoc.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se ha realizado ninguna consulta");
            } else {
                if (createQRYTrec() && createRELTrec()) {
                    JOptionPane.showMessageDialog(null, "Momento de evaluar.");
                } else {
                    JOptionPane.showMessageDialog(null, "Faltan documentos para poder usar el Trec Eva");
                }
            }
        } catch (HeadlessException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_trecBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Menu m = new Menu();
        m.setDefaultCloseOperation(EXIT_ON_CLOSE);
        m.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultaBtn;
    private javax.swing.JButton indexaBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textInfo;
    private javax.swing.JButton trecBtn;
    // End of variables declaration//GEN-END:variables
 public void DeletingAllDocuments() {
        String url = "http://localhost:8983/solr/micoleccion";
        // Preparing Solr Client
        SolrClient Solr = new HttpSolrClient.Builder(url).build();
        try {
            // Delete all
            Solr.deleteByQuery("*");
            Solr.commit();
        } catch (IOException | SolrServerException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        //  Saving the document
        JOptionPane.showMessageDialog(null, "Documents deleted");
    }

    public void indexaDocumento(String index, String title, String author, String text) throws SolrServerException, IOException {
        HttpSolrClient solr = new HttpSolrClient.Builder("http://localhost:8983/solr/micoleccion").build();
        //  Create SolrDocument 
        SolrInputDocument dc = new SolrInputDocument();
        dc.addField("index", index);
        dc.addField("title", title);
        dc.addField("author", author);
        dc.addField("text", text);
        solr.add(dc);
        solr.commit();

    }

    public boolean hasCollection(String url) {
        boolean has = false;
        try ( SolrClient solrClient = new HttpSolrClient.Builder(url).build()) {
            // Use CoreAdminRequest to get the list of collections
            CoreAdminRequest request = new CoreAdminRequest();
            request.setAction(CoreAdminParams.CoreAdminAction.STATUS);

            // Send the request and get the response
            CoreAdminResponse response = request.process(solrClient);

            // Get the list of collections from the response
            int numberOfCollections = response.getCoreStatus().size();
            if (numberOfCollections > 0) {
                has = true;
            }
        } catch (SolrServerException | java.io.IOException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
        return has;
    }

    public void searchDocuments(String desc) throws SolrServerException, IOException {
        HttpSolrClient solr = new HttpSolrClient.Builder("http://localhost:8983/solr/micoleccion").build();
        SolrQuery query = new SolrQuery();
        query.setQuery("*");
        query.addFilterQuery("text: " + desc);
        query.setFields("index", "score");
        QueryResponse rsp = solr.query(query);
        docs = rsp.getResults();
        int tm = docs.size();
        //System.out.println("Tamaño de la consulta: " + tm);
        for (int i = 0; i < tm; i++) {
            textInfo.append(docs.get(i).values().toString() + "\n");
            //  Añadimos el valor de cada consulta al doc global
            trecDoc.add(docs.get(i));
        }
    }

    private boolean createQRYTrec() {
        boolean isCreated = false;
        try {
            String path = "", team = "ETSI", line, document, fichero = "";
            JFileChooser t = new JFileChooser();
            t.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int selection = t.showSaveDialog(null);
            if (selection == JFileChooser.APPROVE_OPTION) {
                path = t.getSelectedFile().getAbsolutePath();
                System.out.println(path);
                fichero = JOptionPane.showInputDialog(null, "Introduzca el nombre del fichero: ") + ".TREC";
                path = path + "\\" + fichero;
            }
            BufferedWriter w = new BufferedWriter(new FileWriter(path));
            int tm = trecDoc.size();
            for (int i = 0; i < tm; i++) {
                document = trecDoc.get(i).getFieldValue("index").toString().replaceAll("[\\[\\](){}]", "");
                line = "1 Q0" + " " + document + " " + i + " " + trecDoc.get(i).getFieldValue("score") + " " + team + "\n";
                //  System.out.println(line);
                w.write(line);
            }
            w.close();
            isCreated = true;
            JOptionPane.showMessageDialog(null, "Fichero creado");
        } catch (HeadlessException | IOException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error al crear el QRY.TREC ");
        }
        return isCreated;
    }

    public boolean createRELTrec() {
        boolean isCreated = false;
        try {
            Scanner sc = null;
            String line, path = "", fichero;
            //  Indicate trec directory to save
            JOptionPane.showMessageDialog(null, "Seleccione el directorio donde se guardara el fichero TREC:");
            JFileChooser t = new JFileChooser();
            t.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int selection = t.showSaveDialog(null);
            if (selection == JFileChooser.APPROVE_OPTION) {
                path = t.getSelectedFile().getAbsolutePath();
                System.out.println(path);
                fichero = JOptionPane.showInputDialog(null, "Introduzca el nombre del fichero: ") + ".TREC";
                path = path + "\\" + fichero;
            }
            BufferedWriter w = new BufferedWriter(new FileWriter(path));
            //  open rel file
            JOptionPane.showMessageDialog(null, "Seleccione el fichero REL:");
            JFileChooser fileChooser = new JFileChooser();
            int result = fileChooser.showOpenDialog(null);
            File file = null;
            if (result == JFileChooser.APPROVE_OPTION) {
                file = fileChooser.getSelectedFile();
            }
            BufferedReader r = new BufferedReader(new FileReader(file));
            while ((line = r.readLine()) != null) {
                String[] parts = line.split("\\s+");
                if (parts.length == 5) {
                    parts[0]=parts[1];
                    parts[3]=parts[2];
                    parts[2]=parts[1];
                    parts[1]="0";
                    w.write(parts[0]+" "+parts[1]+" "+parts[2]+" "+parts[3]+"\n");
                }
            }
            isCreated=true;
        } catch (Exception e) {
        }
        return isCreated;
    }
    /* private boolean createRELTrec() {
        boolean isCreated = false;
        try {
            Scanner sc = null;
            String line = "", path = "", fichero;
            //  Indicate trec directory to save
            JOptionPane.showMessageDialog(null, "Seleccione el directorio donde se guardara el fichero TREC:");
            JFileChooser t = new JFileChooser();
            t.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int selection = t.showSaveDialog(null);
            if (selection == JFileChooser.APPROVE_OPTION) {
                path = t.getSelectedFile().getAbsolutePath();
                System.out.println(path);
                fichero = JOptionPane.showInputDialog(null, "Introduzca el nombre del fichero: ") + ".TREC";
                path = path + "\\" + fichero;
            }
            BufferedWriter w = new BufferedWriter(new FileWriter(path));
            //  Open file Trec
            JOptionPane.showMessageDialog(null, "Seleccione el fichero REL:");
            JFileChooser fileChooser = new JFileChooser();
            int result = fileChooser.showOpenDialog(null);
            File file = null;
            if (result == JFileChooser.APPROVE_OPTION) {
                file = fileChooser.getSelectedFile();
            }

            sc = new Scanner(file);
            while (sc.hasNextLine()) {
                line = sc.nextLine();
                 line = convertRELFormat(line);
                w.write(line + "\n");
            }
            w.close();
            isCreated = true;
        } catch (HeadlessException | IOException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Error al realizar consulta.");
        }
        return isCreated;
    }
     */
 /*  private String convertRELFormat(String line) {
        String l="";
        line = line.replaceAll("0.000000", "");
       String[]elements = line.split(" ");
        for (int i = 0; i < elements.length; i++) {
            System.out.println("e: "+i+": "+elements[i]);
        }
        return l;
    }*/
}
